thesisch04test1.pdf: thesisch04test1.tex
	pdflatex thesisch04test1.tex
	makeindex thesisch04test1.idx
	pdflatex thesisch04test1.tex

# don't remember post-fix
thesisch04test1: thesisch04test1.tex
	pdflatex thesisch04test1
	makeindex thesisch04test1
	pdflatex thesisch04test1
