#+title: BLFS reading notes

* BLFS
from: [[http://www.linuxfromscratch.org/blfs/]]
from: [[http://www.linuxfromscratch.org/blfs/view/9.0/]]

I mainly use this manual to check my knowledge about Linux Utility

**** Ch04 Security

***** TODO read it

**** Ch05 File system and Disk Management

most of tools are to handle filesystem, not very useful for my case

**** Ch06 Editors

I have vim and emacs, which is enough as editor

**** Ch07 shells

most likely use Bash and Zsh

**** Ch08 Virtualization

***** TODO this is a tool I have never integrated into my system, since I use Linux in VMware

*** III. General Libraries and Utilities

**** Ch09 General Libraries
**** Ch10 Graphics and Font Libraries
**** Ch11 General Utilities
**** Ch12 System Utilities
**** Ch13 Programming

*** IV. Networking
**** Ch14 Connecting to a Network
**** Ch15 Networking Programs
**** Ch16 Networking Utiliteis
**** Ch17 Networking Libraries
**** Ch18 Text Web Browers
**** Ch19 Mail/News Clients

*** V. Servers

**** Ch20 Major Servers
- Apache-2.4.41
- BIND-9.14.5
- ProFTPD-1.3.6
- vsftpd-3.0.3
**** Ch21 Mail Server Software
for my personal use, given that self-host email is not that popular, use Gmail service

- Dovecot-2.3.7.2
- Exim-4.92.1
- Postfix-3.4.6
- sendmail-8.15.2
**** Ch22 Databases
- Berkeley DB-5.3.28
- lmdb-0.9.24
- MariaDB-10.4.7
- PostgreSQL-11.5
- SQLite-3.29.0
**** Ch23 Other Server Software
- OpenLDAP-2.4.48
- Unbound-1.9.2

*** VI. X + Window and Display Managers

**** Ch24. X Window System Environment
**** Ch25. X Libraries
**** Ch26. Display Managers
**** Ch27. Window Managers
**** Ch28. Icons

*** VII. KDE
**** 29. Introduction to KDE
**** 30. KDE Frameworks 5
**** 31. KDE Frameworks 5 Based Applications
**** 32. KDE Plasma 5

*** VIII. GNOME
**** 1. GNOME Libraries and Desktop
**** 2. GNOME Applications

*** IX. Xfce
**** 35. Xfce Desktop
**** 36. Xfce Applications
*** X. LXDE
**** 37. LXDE Desktop
**** 38. LXDE Applications

*** XI. X Software

**** Ch39. Office Programs
     - LibreOffice
     ...

**** Ch40. Graphical Web Browsers
     Firefox
     ...
**** Ch41. Other X-based Programs
     - feh
     - rxvt
     ...

*** XII. Multimedia
**** Ch42. Multimedia Libraries and Drivers
     - alsa
     ...
**** Ch43. Audio Utilities
**** Ch44 Video Utilities
     - FFmpeg
     - MPlayer
     - VLC
**** Ch45. CD/DVD-Writing Utilities
*** XIII. Printing, Scanning and Typesetting

* System Administrator's Guild from redhat.com

**** Ch10 Managing Services with systemd
```
#+begin_src
    ## man systemctl
    systemctl enable name.service
    systemctl disable name.service
    systemctl status name.service
    systemctl list-unit-files --type service
    systemctl list-dependencies --after
    systemctl list-dependencies --before
#+end_src

a list of servicen within Kali
#+begin_src shell
    UNIT                               LOAD   ACTIVE SUB     DESCRIPTION
    accounts-daemon.service            loaded active running Accounts Service
    alsa-restore.service               loaded active exited  Save/Restore Sound Card State
    alsa-state.service                 loaded active running Manage Sound Card State (restore and store)
    binfmt-support.service             loaded active exited  Enable support for additional executable binary formats
    colord.service                     loaded active running Manage, Install and Generate Color Profiles
    console-setup.service              loaded active exited  Set console font and keymap
    cron.service                       loaded active running Regular background program processing daemon
    dbus.service                       loaded active running D-Bus System Message Bus
    gdm.service                        loaded active running GNOME Display Manager
    haveged.service                    loaded active running Entropy daemon using the HAVEGE algorithm
    ifupdown-pre.service               loaded active exited  Helper to synchronize boot up for ifupdown
    keyboard-setup.service             loaded active exited  Set the console keyboard layout
    kmod-static-nodes.service          loaded active exited  Create list of required static device nodes for the current kernel
    ModemManager.service               loaded active running Modem Manager
    networking.service                 loaded active exited  Raise network interfaces
    NetworkManager.service             loaded active running Network Manager
    polkit.service                     loaded active running Authorization Manager
    rsyslog.service                    loaded active running System Logging Service
    rtkit-daemon.service               loaded active running RealtimeKit Scheduling Policy Service
    smartd.service                     loaded failed failed  Self Monitoring and Reporting Technology (SMART) Daemon
    stunnel4.service                   loaded active exited  LSB: Start or stop stunnel 4.x (TLS tunnel for network daemons)
    systemd-journal-flush.service      loaded active exited  Flush Journal to Persistent Storage
    systemd-journald.service           loaded active running Journal Service
    systemd-logind.service             loaded active running Login Service
    systemd-modules-load.service       loaded active exited  Load Kernel Modules
    systemd-random-seed.service        loaded active exited  Load/Save Random Seed
    systemd-remount-fs.service         loaded active exited  Remount Root and Kernel File Systems
    systemd-sysctl.service             loaded active exited  Apply Kernel Variables
    systemd-sysusers.service           loaded active exited  Create System Users
    systemd-timesyncd.service          loaded active running Network Time Synchronization
    systemd-tmpfiles-setup-dev.service loaded active exited  Create Static Device Nodes in /dev
    systemd-tmpfiles-setup.service     loaded active exited  Create Volatile Files and Directories
    systemd-udev-trigger.service       loaded active exited  udev Coldplug all Devices
    systemd-udevd.service              loaded active running udev Kernel Device Manager
    systemd-update-utmp.service        loaded active exited  Update UTMP about System Boot/Shutdown
    systemd-user-sessions.service      loaded active exited  Permit User Sessions
    udisks2.service                    loaded active running Disk Manager
    upower.service                     loaded active running Daemon for power management
    user-runtime-dir@1000.service      loaded active exited  User Runtime Directory /run/user/1000
    user-runtime-dir@132.service       loaded active exited  User Runtime Directory /run/user/132
    user@1000.service                  loaded active running User Manager for UID 1000
    user@132.service                   loaded active running User Manager for UID 132
    wpa_supplicant.service             loaded active running WPA supplicant

    LOAD   = Reflects whether the unit definition was properly loaded.
    ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
    SUB    = The low-level unit activation state, values depend on unit type.

    43 loaded units listed. Pass --all to see loaded but inactive units, too.
    To show all installed unit files use 'systemctl list-unit-files'.
#+end_src
