b main
b 120 if i==1 && j==3
r

define pmyArray
    output myArray[0][0]
    output myArray[0][1]
    output myArray[0][2]
    output myArray[0][3]
    output myArray[0][4]
    echo \n
    output myArray[1][0]
    output myArray[1][1]
    output myArray[1][2]
    output myArray[1][3]
    output myArray[1][4]
    echo \n
    output myArray[2][0]
    output myArray[2][1]
    output myArray[2][2]
    output myArray[2][3]
    output myArray[2][4]
    echo \n
    output myArray[3][0]
    output myArray[3][1]
    output myArray[3][2]
    output myArray[3][3]
    output myArray[3][4]
    echo \n
    output myArray[4][0]
    output myArray[4][1]
    output myArray[4][2]
    output myArray[4][3]
    output myArray[4][4]
    echo \n
end

define pmyArrayNext
    output myArrayNext[0][0]
    output myArrayNext[0][1]
    output myArrayNext[0][2]
    output myArrayNext[0][3]
    output myArrayNext[0][4]
    echo \n
    output myArrayNext[1][0]
    output myArrayNext[1][1]
    output myArrayNext[1][2]
    output myArrayNext[1][3]
    output myArrayNext[1][4]
    echo \n
    output myArrayNext[2][0]
    output myArrayNext[2][1]
    output myArrayNext[2][2]
    output myArrayNext[2][3]
    output myArrayNext[2][4]
    echo \n
    output myArrayNext[3][0]
    output myArrayNext[3][1]
    output myArrayNext[3][2]
    output myArrayNext[3][3]
    output myArrayNext[3][4]
    echo \n
    output myArrayNext[4][0]
    output myArrayNext[4][1]
    output myArrayNext[4][2]
    output myArrayNext[4][3]
    output myArrayNext[4][4]
    echo \n
end
