# Makefile for FnArgCnt pass
# Path to top level of LLVM hierarchy
# cd lib/Transforms/FnArgCnt

LEVEL = ../../..
# Name of the library to build
LIBRARYNAME = LLVMFnArgCnt

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
